### ISSUE TITLE
Issue with Menu

### ISSUE THREAD

**Issue by ravihariharan** [primefaces/poseidon#2]
## 1) Environment
- version: poseidon-1.0.0

- Affected browsers: Tested in IE , Chrome and Firefox (looks like all browsers )

## 2) Expected behavior
menu-button -- fa-angle-left should always work
![image](https://cloud.githubusercontent.com/assets/15189434/24323271/95be0c66-1149-11e7-9be5-67baf138555c.png)

...

## 3) Actual behavior
menu-button -- fa-angle-left does not work when there is a button click that has **update="@(form)"**.

An in case of Horizontal Menu the links for e.g. Themes and Menu Mode stop working after the first click.
![image](https://cloud.githubusercontent.com/assets/15189434/24323338/909056c6-114a-11e7-8d2b-b70b5993a39d.png)

..

## 4) Steps to reproduce
Place a button in form

```
<p:commandButton value="Ajax Submit" id="ajax"
							action="#{buttonView.buttonAddLabel}"
							update="@(form)"
							styleClass="ui-priority-primary" />
```

1. Click after place load , Menu working
2. Click on button , Menu not working
3. Click again on the button , Menu working
4. Click again on the button , Menu not working

looks like it works after alternate click.
.. 

## 5) Sample XHTML
Use the empty.xhtml from poseidon-1.0.0.war

```
<ui:define name="content">
		<div class="ui-g">
			<div class="ui-g-12">
				<div class="card">
					<h1>Empty Page</h1>
					<p>Use this page to start from scratch and place your custom
						content.</p>
					<p:button outcome="dashboard" value="Home"
						style="display:inline-block;margin-top:5px" />

					<h:form id="form">
						<p:commandButton value="Ajax Submit" id="ajax"
							action="#{buttonView.buttonAddLabel}" update="@(form)" />
					</h:form>
				</div>
			</div>
		</div>

	</ui:define>
```
..

## 6) Sample bean
No change to ButtonView.java from poseidon-1.0.0.war
..

**Comment by ravihariharan** [comment]
An in case of Horizontal Menu the links for e.g. Themes and Menu Mode stop working all after the first click.

**Comment by mertsincan** [comment]
Details; https://forum.primefaces.org/viewtopic.php?f=43&t=50157&p=154164#p154164

**Comment by ravihariharan** [comment]
Menu part fixed using 
`this.menuButton.off('click').on('click', function(e)`

But issue still exists for 
![image](https://cloud.githubusercontent.com/assets/15189434/24364523/03e48a9c-12e1-11e7-91fd-043b73c915a6.png)
